### ISSUE TITLE
Templated values in model config causes training to crash on start

### ISSUE THREAD

**Issue by gauthiermartin** [sonia-auv/airflow-etl#101]
## Priority

- [ ] low
- [ ] medium
- [X] high
- [ ] critical

## Expected Behavior
Batch size an epoch count value should be replace as int not str

## Current Behavior
Batch size and Epoch count value are replace as string which make it impossible to be
parsed by the training script

## Possible Solution
We must change how the values are replaced in the template

**Comment by 0x72D0** [comment]
no longer relevant
