### ISSUE TITLE
ERROR: unexpected error - Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS 

### ISSUE THREAD

**Issue by gauthiermartin** [sonia-auv/airflow-etl#102]
## Priority

- [ ] low
- [ ] medium
- [X] high
- [ ] critical

## Expected Behavior
We need to unify google cloud account logging issue

## Current Behavior
While running dvc push we get this error message 

ERROR: unexpected error - Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started

## Possible Solution
Unknown

**Comment by 0x72D0** [comment]
no longer using DVC
